#version 430

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer InputBuffer1 {
	float inputArray1[];
};

layout(std430, binding = 1) buffer InputBuffer2 {
	float inputArray2[];
};

layout(std430, binding = 2) buffer OutputBuffer {
	float outputArray[];
};

void main() {
    uint index = gl_GlobalInvocationID.x;
    
    if (index < 1000) {
        outputArray[index] = inputArray1[index] + inputArray2[index];
    }
}

